version: '3'

services:
  cve202232213:
    image: node:16-alpine
    tty: true
    container_name: cve202232213
    ports:
      - "80:80"
    volumes:
      - "./:/app"

    entrypoint:
      - "node /app/testServer.js"