id: product_countdown_for_woocommerce-3f1a34cc-a961-4bcd-a95c-ae6009f1f274

info:
  name: >
    Product Time Countdown for WooCommerce <= 1.6.2 - Authenticated (Contributor+) Stored Cross-Site Scripting
  author: topscoder
  severity: low
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/3f1a34cc-a961-4bcd-a95c-ae6009f1f274?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/product-countdown-for-woocommerce/"
    google-query: inurl:"/wp-content/plugins/product-countdown-for-woocommerce/"
    shodan-query: 'http.html:"wp-content/plugins/product-countdown-for-woocommerce/"'
  tags: cve,wordpress,wp-plugin,product-countdown-for-woocommerce,low,candidate

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/product-countdown-for-woocommerce/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "product-countdown-for-woocommerce"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.6.2')