id: product_table_for_woocommerce-e8ec1bc6-cca5-4b0a-944c-47de0fa46ec9

info:
  name: >
    Product Table For WooCommerce <= 1.2.4 - Authenticated (Contributor+) PHP Object Injection
  author: topscoder
  severity: low
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/e8ec1bc6-cca5-4b0a-944c-47de0fa46ec9?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/product-table-for-woocommerce/"
    google-query: inurl:"/wp-content/plugins/product-table-for-woocommerce/"
    shodan-query: 'http.html:"wp-content/plugins/product-table-for-woocommerce/"'
  tags: cve,wordpress,wp-plugin,product-table-for-woocommerce,low,candidate

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/product-table-for-woocommerce/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag:\\s*([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "product-table-for-woocommerce"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.2.4')