id: grandconference_custom_post-fa0b8026-5c7b-4a4a-93a7-3931da3e3967

info:
  name: >
    Grand Conference Theme Custom Post Type <= 2.6.3 - Missing Authorization
  author: topscoder
  severity: high
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/fa0b8026-5c7b-4a4a-93a7-3931da3e3967?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/grandconference-custom-post/"
    google-query: inurl:"/wp-content/plugins/grandconference-custom-post/"
    shodan-query: 'http.html:"wp-content/plugins/grandconference-custom-post/"'
  tags: cve,wordpress,wp-plugin,grandconference-custom-post,high,candidate

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/grandconference-custom-post/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "grandconference-custom-post"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 2.6.3')