name: Nuclei-Templates-Collecter

on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches:
      - main

# Actions project permission
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.0'  # Specify the version of Go you want to use

    - name: Installing tar and nucleihub via binary
      run: |
        sudo apt install tar

        wget https://github.com/rix4uni/nucleihub/releases/download/v0.0.3/nucleihub-linux-amd64-0.0.3.tgz
        tar -xvzf nucleihub-linux-amd64-0.0.3.tgz
        rm -rf nucleihub-linux-amd64-0.0.3.tgz
        mv nucleihub /usr/local/bin/nucleihub

        wget -P nuclei https://github.com/projectdiscovery/nuclei/releases/download/v3.3.7/nuclei_3.3.7_linux_amd64.zip
        unzip nuclei/nuclei_3.3.7_linux_amd64.zip -d nuclei
        mv nuclei/nuclei /usr/local/bin/nuclei
        rm -rf nuclei

    - name: Running nucleihub
      run: |
        # Step 1
        curl -s "https://raw.githubusercontent.com/rix4uni/nucleihub/refs/heads/main/reponames.txt" | nucleihub updatecheck | grep "Updated today:" | sed 's/^\Updated today: //' | nucleihub download --output-directory nucleihub-downloaded-repos

        # Step 2
        nucleihub duplicate --input-directory nucleihub-downloaded-repos --output-directory nucleihub-templates --large-content

        # Step 3
        rm -rf nucleihub-downloaded-repos

    - name: Commit and push changes if there are any
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git add .
        
        # Check if there are changes before committing
        if ! git diff --cached --exit-code; then
          IST_DATE=$(TZ='Asia/Kolkata' date +'%a %b %d %H:%M:%S IST %Y')
          git commit -m "Updated List: $IST_DATE"
          git push
        else
          echo "No changes to commit"
        fi
