id: animated-icon-banner-for-visual-composer-18d052b04543a65e7e92ce56e05e0ea3

info:
  name: >
    Essential Doo Components for Visual Composer <= 1.9 - Authenticated (Contributor+) Stored Cross-Site Scripting
  author: topscoder
  severity: low
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/cb3f3bc7-9127-43ba-80ad-e32fd7c3b05e?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/animated-icon-banner-for-visual-composer/"
    google-query: inurl:"/wp-content/plugins/animated-icon-banner-for-visual-composer/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,animated-icon-banner-for-visual-composer,low

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/animated-icon-banner-for-visual-composer/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "animated-icon-banner-for-visual-composer"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.9')