name: Daily Update Nuclei POCs

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: 1 Clone Repos
      run: python 1-clone_repos.py

    - name: 2 Download Nuclei
      run: |
        pip install requests
        python 2-download_nuclei.py
        unzip nuclei.zip nuclei
        chmod +x nuclei
        rm -rf nuclei.zip
    - name: 3 Delete Duplicated
      run: python 3-delete_duplicated.py
        
    - name: 4 Move File
      run: python 4-move_file.py

    - name: 5 Check POC
      run: bash 5-check_poc.sh
      
    - name: 6 Get Count
      run: python 6-get_count.py
      
    - name: 7 Get POC Name
      run: python 7-get_pocname.py

    - name: 8 Delete Nuclei
      run: rm -rf nuclei
      
    - name: Commit and Push changes
      run: |
        echo $(date +'%Y%m%d') > date.txt
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -am "$(date +'%Y%m%d')"
        git push -v --progress
