id: product_category_tree-88840d66-1644-4af0-b811-41f0e9fe2c0c

info:
  name: >
    Product Category Tree <= 2.5 - Missing Authorization
  author: topscoder
  severity: high
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/88840d66-1644-4af0-b811-41f0e9fe2c0c?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/product-category-tree/"
    google-query: inurl:"/wp-content/plugins/product-category-tree/"
    shodan-query: 'http.html:"wp-content/plugins/product-category-tree/"'
  tags: cve,wordpress,wp-plugin,product-category-tree,high,candidate

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/product-category-tree/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "product-category-tree"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 2.5')