id: product_import_export_for_woo-d4464bb1-273a-42c4-a7ec-8e123d286963

info:
  name: >
    Product Import Export for WooCommerce <= 2.5.0 - Authenticated (Admin+) PHP Object Injection via form_data Parameter
  author: topscoder
  severity: low
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/d4464bb1-273a-42c4-a7ec-8e123d286963?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/product-import-export-for-woo/"
    google-query: inurl:"/wp-content/plugins/product-import-export-for-woo/"
    shodan-query: 'http.html:"wp-content/plugins/product-import-export-for-woo/"'
  tags: cve,wordpress,wp-plugin,product-import-export-for-woo,low,candidate

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/product-import-export-for-woo/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "product-import-export-for-woo"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 2.5.0')