id: tmm_content_composer-7773fcc3049ab8149d29da7a15766c25

info:
  name: >
    ThemeMakers Visual Content Composer <= 1.5.8 - Unauthenticated PHP Object Injection
  author: topscoder
  severity: critical
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/dd072cc6-cc32-40b2-af00-adef333d675a?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/tmm_content_composer/"
    google-query: inurl:"/wp-content/plugins/tmm_content_composer/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-plugin,tmm_content_composer,critical

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/tmm_content_composer/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "tmm_content_composer"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.5.8')